module.exports = [
  {
    id: 0,
    name: "Bienvenue, Dresseur",
    description: "Creer son compte PokeFlip.",
    emoji: "👋",
    hint: "Cree ton compte.",
    rewards: { xp: 10 },
  },
  {
    id: 1,
    name: "Premiere victoire",
    description: "Remporter une premiere partie en ligne.",
    emoji: "🎯",
    hint: "Gagne une partie en ligne.",
    rewards: { xp: 10 },
  },
  {
    id: 2,
    name: "Sur la lancee",
    description: "Atteindre cinq victoires en ligne.",
    emoji: "💪",
    hint: "Gagne 5 parties en ligne.",
    rewards: { xp: 25 },
  },
  {
    id: 3,
    name: "Inarretable",
    description: "Atteindre dix victoires en ligne.",
    emoji: "🔥",
    hint: "Gagne 10 parties en ligne.",
    rewards: { xp: 50 },
  },
  {
    id: 10,
    name: "Double XP",
    description: "Terminer une partie pendant le week-end.",
    emoji: "💰",
    hint: "Joue pendant un week-end.",
    rewards: { xp: 10 },
  },
  {
    id: 100,
    name: "Zekrom",
    description: "Trouver une paire de Zekrom.",
    emoji:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/644.png",
    hint: "Trouve la paire numero 644.",
    rewards: { colors: ["color-zekrom"] },
  },
  {
    id: 150,
    name: "Niveau maximum",
    description: "Atteindre le niveau 5.",
    emoji: "💯",
    hint: "Atteins le niveau maximum.",
    rewards: { xp: 0 },
  },
  {
    id: 200,
    name: "Une chance sur 8192",
    description: "Trouver une paire shiny.",
    emoji: "🌟",
    hint: "Trouve une paire shiny.",
    rewards: { xp: 50, colors: ["color-shiny"] },
  },
];
